### ISSUE TITLE
Working version

### ISSUE THREAD

**Issue by psychemedia** [psychemedia/jupyterserverproxy-datasette-demo#2]
Patches to `datatasette` by @simonw  and a PR to this repo got things working.

Other issues along the way that may or may not need addressing in this repo so that it fully works:

- facet URLs: https://github.com/simonw/datasette/issues/712

**Comment by simonw** [comment]
The facet URLs bug should be fixed by #3

Still needed is a mechanism to not have to hard-code in the name of the database file: https://github.com/simonw/jupyterserverproxy-datasette-demo/issues/2

**Comment by simonw** [comment]
I'm going to take another look at https://github.com/simonw/datasette/pull/672 for that.

**Comment by simonw** [comment]
Added some notes to https://github.com/simonw/jupyterserverproxy-datasette-demo/issues/2

**Comment by yuvipanda** [comment]
This works now, right?
